const config = {
  STREETVIEW_API_KEY: process.env.REACT_APP_STREETVIEW_API_KEY,
  STREETVIEW_SIGNATURE: process.env.REACT_APP_STREETVIEW_SIGNATURE,
  MAPBOX_API_KEY: process.env.REACT_APP_MAPBOX_API_KEY,
  CENSUS_API_KEY: process.env.CENSUS_API_KEY
}

export default config;